### ISSUE TITLE
How to run ONLY tslint?

### ISSUE THREAD

**Issue by stevenmusumeche** [wmonk/create-react-app-typescript#144]
Is there a way that I can run tslint directly without running the build command?

**Comment by wmonk** [comment]
Potentially
 ```
`npm bin`/tslint
```

**Comment by sebald** [comment]
You could add a `script` to your `package.json`. For example:

```
"lint": "tslint --type-check --exclude **/*.d.ts src/**/*.ts src/**/*.tsx",
```

**Comment by stevenmusumeche** [comment]
That does work, however it appears we need to update the tslint version to the latest? I am getting this error which seems to be fixed in later versions?

```
TypeError: Cannot read property 'flags' of undefined
    at Object.getCheckFlags (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/typescript/lib/typescript.js:10137:22)
    at getTypeOfSymbol (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/typescript/lib/typescript.js:30957:20)
    at getTypeOfNode (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/typescript/lib/typescript.js:47329:24)
    at Object.getTypeAtLocation (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/typescript/lib/typescript.js:26823:31)
    at getImplicitType (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/tslint/lib/rules/noUnusedVariableRule.js:269:24)
    at cb (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/tslint/lib/rules/noUnusedVariableRule.js:259:20)
    at visitEachNode (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/typescript/lib/typescript.js:15956:30)
    at Object.forEachChild (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/typescript/lib/typescript.js:16143:24)
    at cb (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/tslint/lib/rules/noUnusedVariableRule.js:264:19)
    at visitNode (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/typescript/lib/typescript.js:15944:20)
```

**Comment by sebald** [comment]
I didn't install `tslint` on my own, since it comes with the `react-scripts-ts` :)

**Comment by stevenmusumeche** [comment]
Yes, that's what I mean.  The version of tslint in this repo is an older one.  I'm requesting that it be updated to (maybe) solve this issue.

**Comment by sebald** [comment]
But I have an old `tslint` too then and it works. My lock files tells me that for the dependency: `tslint@^5.2.0` it installed version 5.5.0.

Guess this is a more general issue with tslint: https://github.com/palantir/tslint/issues/3001

**Comment by YagoLopez** [comment]
Excuse my offtopic but I would like just the contrary. How can I run (not build) the app without tslint? thanks

**Comment by patrickmdnet** [comment]
To run lint without build, you can run the version of `tslint` that's part of your package.

    node_modules\.bin\tslint --type-check --project .

**Comment by stevenmusumeche** [comment]
@patrickmdnet that does work, however it causes the same error I posted above

```
Stevens-MacBook-Pro-2:embed stevenmusumeche$ ./node_modules/.bin/tslint --type-check --project .
TypeError: Cannot read property 'flags' of undefined
    at Object.getCheckFlags (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/typescript/lib/typescript.js:10137:22)
    at getTypeOfSymbol (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/typescript/lib/typescript.js:30957:20)
    at getTypeOfNode (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/typescript/lib/typescript.js:47329:24)
    at Object.getTypeAtLocation (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/typescript/lib/typescript.js:26823:31)
    at getImplicitType (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/tslint/lib/rules/noUnusedVariableRule.js:269:24)
    at cb (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/tslint/lib/rules/noUnusedVariableRule.js:259:20)
    at visitEachNode (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/typescript/lib/typescript.js:15956:30)
    at Object.forEachChild (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/typescript/lib/typescript.js:16143:24)
    at cb (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/tslint/lib/rules/noUnusedVariableRule.js:264:19)
    at visitNode (/Users/stevenmusumeche/conversations-embed-v3/embed/node_modules/typescript/lib/typescript.js:15944:20)
```
