### ISSUE TITLE
Error: Cannot find module '/home/user/test/node_modules/jest-cli'

### ISSUE THREAD

**Issue by comerc** [wmonk/create-react-app-typescript#154]
### Environment

1. `npm ls react-scripts-ts` (if you haven’t ejected): └── (empty)
2. `node -v`: v8.4.0
3. `npm -v`: 5.3.0
4. `yarn --version` (if you use Yarn): 0.27.5
5. `npm ls react-scripts-ts` (if you haven’t ejected): 

1. Operating system: Ubuntu 14.04

### Steps to Reproduce

1. create-react-app test --scripts-version=react-scripts-ts
2. cd test && npm install
3. npm run eject
4. npm run test

```
> node scripts/test.js --env=jsdom

module.js:491
    throw err;
    ^

Error: Cannot find module '/home/user/test/node_modules/jest-cli'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at getJest (/home/user/test/node_modules/jest/node_modules/jest-cli/build/cli/getJest.js:22:12)
    at Object.run (/home/user/test/node_modules/jest/node_modules/jest-cli/build/cli/index.js:39:48)
    at Object.<anonymous> (/home/user/test/scripts/test.js:27:6)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
```

**Comment by wmonk** [comment]
Hmm, not sure why this happens. Is `jest` listed in your `package.json`?

**Comment by abenchi** [comment]
I have the same error

**Comment by jiverson** [comment]
Fyi I think it is this issue https://github.com/facebook/jest/issues/4419

**Comment by danjme** [comment]
Need to add jest as a dependency / package to the project as it's currently not included and will fail to run.

All tests pass failing that.

**Comment by ryanbrainard** [comment]
Deleting my `node_modules` and reinstalling them fixed it for me. I was playing around with `yarn` and `npm` together and I think so wires got crossed.

**Comment by amackintosh** [comment]
Confirmed, wiping node_modules and doing `yarn install` fixed mine.

It works again following that as `yarn test`.

I have a feeling my reason was the same as ryanbrainard's. I also mixed a bit of npm and yarn along the way.

**Comment by andela-ksolomon** [comment]
@ryanbrainard  and @amackintosh Thanks for this. I also came across the same issue, I think the best way to stay away from this issue is to stick with one package manager.

`rm -rf node_modules/ && yarn install` solved mine

**Comment by TallOrderDev** [comment]
Just ran into this too... blowing away node modules and running yarn install again fixed this. Not sure why this happened!

**Comment by lsemerini** [comment]
I had this issue today, and as @ryanbrainard mentioned, it was because I installed something with `npm` and before I did with `yarn`. So mixing both together caused this.

And yes, wiping out `node_modules` fixed it.

**Comment by atopus** [comment]
Same here : fixed by removing `node_modules` and reinstalling with `yarn install`.

Thanks :)

**Comment by sanchit94** [comment]
I bumped into this even though I was just using npm, so it is probably not just about mixing package manages. But thanks guys for the fix it worked like magic!

**Comment by khanhhd** [comment]
Thanks @ryanbrainard

**Comment by Reebby** [comment]
awesome this worked like a charm 
rm -rf node_modules/ && yarn install
thanks @andela-ksolomon

**Comment by nour-s** [comment]
Removing node_modules solved mine too! Very weird!
