### ISSUE TITLE
Error: Cannot find module 'typescript'

### ISSUE THREAD

**Issue by ggsjyoon** [wmonk/create-react-app-typescript#241]
```
$ yarn start
yarn run v1.3.2
$ react-scripts-ts start
module.js:544
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\mms\mms-ui\node_modules\fork-ts-checker-webpack-plugin\lib\CancellationToken.js:6:10)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\mms\mms-ui\node_modules\fork-ts-checker-webpack-plugin\lib\index.js:10:25)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Upgraded to 2.13.0 and started getting the error above. I'm not sure it's a bug or not. Can someone help me please?

I've tried `yarn cache clean` and then `yarn install` but that did not work either.

**Comment by caghand** [comment]
Yeah, I have mentioned this problem in https://github.com/wmonk/create-react-app-typescript/pull/165#issuecomment-359512965. :)

**Comment by ggsjyoon** [comment]
Thanks.
