### ISSUE TITLE
Update webpack-dev-server

### ISSUE THREAD

**Issue by tomashubelbauermicrosoft** [wmonk/create-react-app-typescript#437]
I am running into an issue in CRA TS which seems to be caused by an outdated `webpack-dev-server` dependency. The issue is node/issues#21665 and it used to occur in CRA too as it was also using an outdated version of the dependency [and has since updated it](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/package.json#L71). CRA TS is still using an affected version and the issue reproduces for me in CRA TS:

1. `create-react-app repro --scripts-version=react-scripts-ts`
2. `cd repro`
3. Create a `.env` file and place `HTTPS=true` in it
4. `npm start`
5. Bypass the security warning in Chrome
6. Keep refreshing until the issue occurs (~3 times)

```
internal/stream_base_commons.js:62
  var err = req.handle.writev(req, chunks, allBuffers);
                       ^

TypeError: req.handle.writev is not a function
    at writevGeneric (internal/stream_base_commons.js:62:24)
    at Socket._writeGeneric (net.js:711:5)
    at Socket._writev (net.js:720:8)
    at doWrite (_stream_writable.js:408:12)
    at clearBuffer (_stream_writable.js:517:5)
    at Socket.Writable.uncork (_stream_writable.js:314:7)
    at connectionCorkNT (_http_outgoing.js:641:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I believe the fix would be to update `webpack-dev-server` the same way. For me this happens on Windows but it should happen under the same conditions described in the linked issue for anyone.

**Comment by tomashubelbauermicrosoft** [comment]
Upon further research it seems this issue may be reoccurring in CRA: facebook/create-react-app#5003.

**Comment by dnicoara-psft** [comment]
i'm having the same issue. I've installed recently node 10 and since then...

**Comment by tomashubelbauermicrosoft** [comment]
I have switched to CRA 2.1 which added TypeScript support and came out a few days back, that may be an option for you as well, @dnicoara-psft. [*Migrating from create-react-app-typescript to Create React App*](https://vincenttunru.com/migrate-create-react-app-typescript-to-create-react-app/)

Just an FYI, obviously this issue still stands.

**Comment by tomashubelbauermicrosoft** [comment]
I have not noticed anything of that sort yet, however it's been only a few days. Can you give me a few examples of what is subpar in the CRA version as opposed to the CRA-TS one in terms of linting?

**Comment by Cyberboss** [comment]
Another motivator for the bump: https://www.npmjs.com/advisories/725

**Comment by kmturley** [comment]
<img width="572" alt="screen shot 2018-12-03 at 10 31 08 am" src="https://user-images.githubusercontent.com/1710493/49383420-aec72d80-f6e6-11e8-88f3-530e2ed21630.png">

This is a high warning, needs fixing!!

**Comment by tomashubelbauermicrosoft** [comment]
Alternatively, @wmonk please consider marking the repository as archived, if it is no longer maintained.
If it isn't, that's absolutely fine, but it should be indicated so that people know not to use it for new stuff.

**Comment by MikaelStenstrand** [comment]
Same problem here, any news for a fix?

**Comment by wkillerud** [comment]
The project has been deprecated and was archived at some point (it seems to have been un-archived to update the readme and then not re-archived again). In any case, don't expect this package to be updated @MikaelStenstrand. 

The transition to Create React App was relatively smooth in a project I'm working on, so I recommend making the transition to that project instead. [The guide posted in an earlier comment](https://github.com/wmonk/create-react-app-typescript/issues/437#issuecomment-435413515) was of great help. Good luck! 😄
